from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('Banking/', views.Banking, name='Banking'),
    path('careers/', views.careers, name='careers'),
    path('Website_development/', views.Website_development, name='Website_development'),
    path('developers_and_property_managers/', views.developers_and_property_managers, name='developers_and_property_managers'),
    path('energy_and_resources_industry/', views.energy_and_resources_industry, name='energy_and_resources_industry'),
    path('retail_and_banking/', views.retail_and_banking, name='retail_and_banking'),
    path('general_contractors_program_and_construction_managers/', views.general_contractors_program_and_construction_managers, name='general_contractors_program_and_construction_managers'),
    path('Transportation/', views.Transportation, name='Transportation'),
    path('manufacturing_and_technology_industry/', views.manufacturing_and_technology_industry, name='manufacturing_and_technology_industry'),
    path('Healthcare/', views.Healthcare, name='Healthcare'),
    path('education/', views.education, name='education'),
    path('engineering_design_and_consulting/', views.engineering_design_and_consulting, name='engineering_design_and_consulting'),
    path('government/', views.government, name='government'),
    path('hospitality_industry/', views.hospitality_industry, name='hospitality_industry'),
    path('Product_Overview/', views.Product_Overview, name='Product_Overview'),
    path('Funds/', views.Funds, name='Funds'),
    path('Insurance/', views.Insurance, name='Insurance'),
    path('Pensions/', views.Pensions, name='Pensions'),
    path('Wealth_Management/', views.Wealth_Management, name='Wealth_Management'),
    path('about/', views.about, name='about'),
    path('Asset_Management/', views.Asset_Management, name='Asset_Management'),
    path('contact-us/', views.contact, name='contact-us'),
    path('our-commitments/', views.commitments, name='our-commitments'),
    path('iConcept4_Pro/', views.iConcept4_Pro, name='iConcept4_Pro'),
    path('efass/', views.efass, name='efass'),
    path('RadraPro/', views.RadraPro, name='RadraPro'),
    path('request_demo/', views.request_demo, name='request_demo'),
    path('faqs/', views.faqs, name='faqs'),
    path('shop/', views.shop, name='shop'),
    path('tss/cart/', views.cart, name='cart'),
    path('tss/checkout/', views.checkout, name='checkout'),
    path('process_order/', views.processOrder, name='process_order'),
    path('update/', views.updateItem, name='update'),
]