# Generated by Django 3.0.8 on 2024-06-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_us',
        ),
    ]
