# Generated by Django 3.0.8 on 2024-06-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
